# -*- coding: utf-8 -*-
"""miniproDay2_Web-scrapping

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XPnItvLS0I6PjIGKKADZCDhahmZHNyih
"""

#installing the requents via pip install command
!pip install requests

#import BeautifulSoup from bs4
from bs4 import BeautifulSoup
#the 
import requests
url = 'https://www.flipkart.com/search?q=mobiles&sid=tyy%2C4io&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_1_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_2_1_na_na_ps&as-pos=2&as-type=RECENT&suggestionId=mobiles%7CMobiles&requestId=b5e8ebad-2e7b-4033-82ba-774fdd9d6f9a&as-backfill=on'
page = requests.get(url)

#getting all informations in page as a text
page.text

#parsing as our document type is html
soup = BeautifulSoup(page.text, 'html.parser')
soup.title

#our main code for scrapping, collecting the data for name price rating
name = []
price = []
rating = []
for a in soup.findAll('a', href=True, attrs={'class':'_31qSD5'}):
    model = a.find('div', attrs={'class':'_3wU53n'})
    cost = a.find('div', attrs={'class':'_1vC4OE _2rQ-NK'})
    rating1 = a.find('div', attrs={'class':'hGSR34'})
    name.append(model.text)
    price.append(cost.text)
    rating.append(rating1.text)

#Displaying the names in order to check our data 
name

#Displaying the price in order to check our data 
price

#Displaying the rating in order to check our data 
rating

#importing the pandas as a pd
import pandas as pd
#storing the data in tabular form to display in tables
df = pd.DataFrame(list(zip(name,price,rating)))
df.columns = ['Name', 'Price', 'Rating']

#displaying the table created
df